# Generated by Django 2.1 on 2020-09-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
