# Generated by Django 2.1 on 2020-09-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200908_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='phone',
        ),
        migrations.AddField(
            model_name='extenduser',
            name='cash_earn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='no_referal',
            field=models.IntegerField(default=0),
        ),
    ]
