# Generated by Django 2.1 on 2020-09-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200908_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('UPI_ID', models.CharField(max_length=30)),
                ('paid', models.BooleanField(default=False)),
                ('plan', models.CharField(max_length=30)),
                ('Refer_by', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='referal',
            field=models.CharField(max_length=30),
        ),
    ]
