# Generated by Django 2.1 on 2020-09-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uname',
        ),
    ]
